version: '2'
services:
  db:
    image: postgres:10.1
    ports:
       - "5432:5432"
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=livecoding_development
    command: postgres

  app:
    # use the Dockerfile next to this file
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - /app/node_modules
    # expose the port
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/livecoding_development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  redis:
    image: redis:3-alpine
    ports:
      - "6379:6379"

  sidekiq_worker:
    build: .
    command: sidekiq
    volumes:
      - .:/app
    depends_on:
      - app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/livecoding_development
      - REDIS_URL=redis://redis:6379
